name: Auto Merge to Develop

on:
  push:
    branches:
      - 'feature/**'
      - 'security/**'

permissions:
  contents: write

jobs:
  merge:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout develop branch
        uses: actions/checkout@v4
        with:
          ref: develop
          fetch-depth: 0

      - name: Merge source branch into develop
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"

          echo "Source branch: ${{ github.ref_name }}"

          git fetch origin ${{ github.ref_name }}
          git merge origin/${{ github.ref_name }} --no-ff -m "Auto merge from ${{ github.ref_name }}"
          git push origin develop